### ISSUE TITLE
图像读入

### ISSUE THREAD

**Issue by LhysX** [xiangdeyizhang/OpenCV_sgbm_multiThreads#2]
您好。我有两个问题。
请问图片在哪里读入呢？我在源码里没有找到相关部分。
还有原图片分辨率是640X480还是320X240的？

**Comment by xiangdeyizhang** [comment]
cv::Mat leftsrc  = cv::imread("aloeL.jpg",0);
		cv::Mat rightsrc = cv::imread("aloeR.jpg",0);在ｍａｉｎ函数里面可以查看

**Comment by LhysX** [comment]
感谢回复。
